# Generated by Django 4.2.2 on 2023-10-26 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fefi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('im', models.ImageField(blank=True, upload_to='fefi/pics/%Y/%m/%d')),
                ('video', models.FileField(blank=True, upload_to='fefi/video/%Y/%m/%d')),
                ('audio', models.FileField(blank=True, upload_to='fefi/audio/%Y-%m-%d')),
                ('likes', models.ManyToManyField(blank=True, related_name='fef_like', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fefi.profile')),
            ],
            options={
                'verbose_name_plural': 'fefs',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('repimg', models.ImageField(blank=True, upload_to='fefi/pics/%Y/%m/%d')),
                ('repvideo', models.FileField(blank=True, upload_to='fefi/video/%M/%y/%d')),
                ('audio2', models.FileField(blank=True, upload_to='fefi/audio/%Y/%m/%d')),
                ('fef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='fefi.fef')),
                ('likes', models.ManyToManyField(blank=True, related_name='reply_like', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
