# Generated by Django 4.2.2 on 2023-10-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fefi', '0003_fef_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fef',
            name='owner',
        ),
        migrations.AlterField(
            model_name='fef',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fefi.profile'),
        ),
    ]
