# Generated by Django 4.2.2 on 2023-10-27 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fefi', '0004_remove_fef_owner_alter_fef_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fef',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
