# Generated by Django 4.2.2 on 2023-10-28 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fefi', '0006_alter_fef_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fef',
            options={},
        ),
        migrations.AlterField(
            model_name='fef',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fefs', to=settings.AUTH_USER_MODEL),
        ),
    ]
